dist: bionic

branches:
  only:
    - master

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.local/bin
    - $HOME/.stack

addons:
  apt:
    packages:
      - colordiff               # test
      - libgmp-dev              # GHC
      - qt5-default             # ff-qtah
      - libgirepository1.0-dev  # ff-gtk
      - libgtk-3-dev            # ff-gtk

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - |
    if [ -x ~/.local/bin/stack ]; then
      stack --version
    else
      travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 \
      | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
  - export STACK="stack --no-terminal --install-ghc"

jobs:
  include:
    - stage: build core
      install: $STACK build --test --only-dependencies ff-core
      script: test/script ff-core
    - stage: build
      name: ff (CLI)
      install: $STACK build --test --only-dependencies ff
      script: test/script ff
    - stage: build
      name: ff-gtk (GUI)
      install: $STACK build --test --only-dependencies ff-gtk
      script: test/script ff-gtk
    - stage: build
      name: ff-qtah (GUI)
      install: $STACK build --test --only-dependencies ff-qtah
      script: test/script ff-qtah
    - stage: test
      name: test
      script: test/script
    - stage: test
      name: haddock
      script: $STACK haddock --no-haddock-deps
    - stage: test
      name: hlint
      install: $STACK build hlint
      script: $STACK exec -- hlint .
