name: ff
version: '0.1'

library:
  dependencies:
    - aeson
    - bytestring
    - crdt
    - directory
    - filepath
    - text
  source-dirs: lib

executables:
  ff:
    dependencies:
      - aeson
      - bytestring
      - crdt
      - directory
      - filepath
      - optparse-applicative
      - stm
      - text
      - yaml

      - ff

    main: Main
    source-dirs: exe

tests:
  test:
    dependencies:
      - tasty
      - tasty-hunit

      - ff

    main: Main
    source-dirs: test

dependencies:
  - base
  - containers
