resolver: lts-14.0

packages:
  - ff
  - ff-core
  - ff-gtk
  - ff-qt
  - ff-test

extra-deps:
  # ff-core:
  - crdt-10.4
  - github-0.22
  - git: https://github.com/ff-notes/ron.git
    commit:
      7be4385725be7992e134f65c529845dc927fa7f0  # ron-0.9+, ron-storage-0.10+
    subdirs: [ron, ron-rdt, ron-storage]
  # - ron-0.10
  # - ron-rdt-0.10
  # - ron-storage-0.11
  - ron-schema-0.9

  # ff-gtk:
  - gi-gtk-declarative-0.5.0
  - gi-gtk-declarative-app-simple-0.5.0

  # ff-qt:
  - git: https://gitlab.com/khumba/hoppy.git
    commit:
      45dded1e21c29409a09eb88ec92bd33b4f6ed0f3
      # 0.5.1 + Compatibility with GHC 8.6, Cabal 2.4
    subdirs: [generator, runtime, std]
  - git: https://gitlab.com/cblp/qtah.git
    commit: 53216276acc884fc197a51f07917a5e3526d8bc7  # 0.6.0 + patches
    subdirs: [qtah, qtah-cpp, qtah-generator]

  # gi-gtk-declarative:
  - haskell-gi-0.22.6

  # github:
  - binary-instances-1

  # haskell-gi:
  - gi-atk-2.0.20
  - gi-cairo-1.0.22
  - gi-gdk-3.0.21
  - gi-gdkpixbuf-2.0.22
  - gi-gio-2.0.24
  - gi-glib-2.0.22
  - gi-gobject-2.0.21
  - gi-gtk-3.0.31
  - gi-pango-1.0.21
  - haskell-gi-base-0.22.2

# reduce some deps?
# flags: {comonad: {contravariant: False}}

docker:
  enable: false
  image: ff-ubuntu-16.04

nix:
  packages: [zlib qt5.qtbase gtk3 gobject-introspection]
