resolver: lts-12.0

packages:
  - ff
  - ff-core
  - ff-test

extra-deps:
  # crdt-test:
    - QuickCheck-GenT-0.2.0
  # ff:
    - crdt-10.3
  # ff:test:
    - git: https://github.com/cblp/crdt.git
      commit: 'v10.3'
      subdirs:
        - crdt-test
