resolver: lts-10.6

extra-deps:
  # ff:
    - crdt-9.0
  # ff:test:
    - git: https://github.com/cblp/crdt.git
      commit: f07533d  # 9.0 + 1 commit
      subdirs:
        - crdt-test

# ff-qt -- temporarily disabled
# extra-deps:
#   - git: https://gitlab.com/cblp/qtah.git
#     commit: 913d45b  # master, 2018-01-13
#     subdirs:
#       - qtah
#       - qtah-cpp
#       - qtah-generator
#   # - ../qtah/qtah
#   # - ../qtah/qtah-cpp
#   # - ../qtah/qtah-generator
# flags: {qtah: {qt5: true}, qtah-cpp: {qt5: true}}
