name: ff
version: '0.3'
copyright:
  2018 Yuriy Syrovetskiy, Nikolay Loginov

executable:
  main: Main
  other-modules: Paths_ff

dependencies:
  - base
  - crdt
  - directory
  - filepath
  - gitrev
  - mainland-pretty
  - stm
  - terminal-size

  - ff-core
