name: ff
version: '0.5'
copyright:
  2018 Yuriy Syrovetskiy, Nikolay Loginov

executable:
  main: Main
  other-modules: Paths_ff

dependencies:
  - async
  - base
  - crdt
  - directory
  - extra
  - filepath
  - gitrev
  - mainland-pretty
  - mtl
  - pager
  - stm
  - terminal-size
  - text

  - ff-core
