name: ff-core
copyright:
  2018 Yuriy Syrovetskiy, Nikolay Loginov

library:
  dependencies:
    # global
    - aeson
    - bytestring
    - containers
    - crdt
    - directory
    - extra
    - filepath
    - github
    - hashable
    - mtl
    - optparse-applicative
    - prettyprinter
    - prettyprinter-ansi-terminal
    - random
    - temporary
    - text
    - time
    - typed-process
    - unordered-containers
    - vector
    - yaml

    # organization
    - ron
  source-dirs: lib

tests:
  features:
    dependencies:
      - blaze-html
      - interpolate
    main: Features.hs

dependencies:
  - base
