name: ff-test

dependencies:
  # global
  - aeson
  - base
  - bytestring
  - containers

  # project
  - ff-core

library:
  dependencies:
    - crdt
    - lens
    - mtl
  exposed-modules:
    - FF.Test

tests:
  test:
    dependencies:
      # global
      - errors
      - github
      - hedgehog
      - interpolate
      - tasty
      - tasty-hedgehog
      - tasty-th
      - text
      - time
      - unordered-containers
      - vector

      # organization
      - ron
      - ron-storage

      # package
      - ff-test

    main: Main
    source-dirs: test
