name: ff-test

dependencies:
  # global
  - aeson
  - base
  - bytestring
  - containers

  # project
  - ff-core

tests:
  test:
    dependencies:
      # global
      - errors
      - github
      - hedgehog
      - interpolate
      - tasty
      - tasty-hedgehog
      - tasty-th
      - text
      - time
      - unordered-containers
      - vector

      # organization
      - ron
      - ron-storage

    main: Main
    source-dirs: test
